name: Update Fast VLESS

on:
  schedule:
    # Запуск каждые 15 минут
    - cron: '*/15 * * * *'
  workflow_dispatch: # Позволяет запускать скрипт вручную кнопкой на сайте GitHub

jobs:
  update:
    runs-on: ubuntu-latest
    permissions:
      contents: write # Разрешает GitHub Actions записывать файл обратно в ваш репозиторий

    steps:
    # 1. Скачиваем файлы репозитория на сервер GitHub
    - name: Checkout repository
      uses: actions/checkout@v4

    # 2. Устанавливаем Python
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    # 3. Запускаем ваш скрипт проверки прокси
    - name: Run script
      run: python update_vless.py

    # 4. Сохраняем обновленный fast_vless.txt и отправляем его обратно в гит
    - name: Commit and Push changes
      run: |
        git config --local user.email "github-actions[bot]@://github.com"
        git config --local user.name "github-actions[bot]"
        git add fast_vless.txt
        # Проверяем, изменился ли файл, чтобы не делать пустые коммиты
        git diff --quiet && git diff --staged --quiet || (git commit -m "Update fast VLESS list" && git push)
